[package]
name="kson-editor"
version="0.1.0"
edition = "2018"
authors = ["Emil Draws <emildraws@gmail.com>"]

[dependencies]
ggez = "0.5.1"
imgui = "0.2.1"
imgui-gfx-renderer = "0.2.0"
imgui-winit-support = "0.2.1"
gfx_core = "0.9"
gfx_device_gl = "0.16"
nfd = { git = "https://github.com/SpaceManiac/nfd-rs.git", branch = "zenity" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.3.1"
libmath = "0.2.1"
thread_profiler = "0.3.0"
winit = { version = ">= 0.16, <= 0.19", package = "winit" }
rodio = { version = "0.9", default-features = false, features = ["flac", "vorbis", "wav"] }
serde_cbor = "0.11.1"
kson = { git = "https://github.com/Drewol/kson-rs.git" }

[features]
profiler = ["thread_profiler/thread_profiler"]