[package]
name="kson-editor"
version="0.1.0"
edition = "2018"
authors = ["Emil Draws <emildraws@gmail.com>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.3.1"
libmath = "0.2.1"
thread_profiler = "0.3.0"
rodio = { version = "0.14", default-features = false, features = ["flac", "vorbis", "wav"] }
serde_cbor = "0.11.1"
kson = { git = "https://github.com/Drewol/kson-rs.git" }
directories-next = "2.0.0"
nfd = { git = "https://github.com/SpaceManiac/nfd-rs.git", branch = "zenity" }
anyhow = "1"
nalgebra = "0.28"
log = "0.4.14"
simple_logger = "1.11.0"

[dependencies.eframe]
version = "0.13"
features = ["persistence"]

[features]
profiler = ["thread_profiler/thread_profiler"]