[package]
name="usc-editor"
version="0.1.0"

[dependencies]
ggez = "0.5.1"
imgui = "0.2.1"
imgui-gfx-renderer = "0.2.0"
imgui-winit-support = "0.2.1"
gfx_core = "0.9"
gfx_device_gl = "0.16"
nfd = { git = "https://github.com/EmbarkStudios/nfd-rs.git", branch = "coinitialize-fix" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.3.1"
libmath = "0.2.1"
thread_profiler = "0.3.0"
time_calc = "0.13.0"
winit = { version = ">= 0.16, <= 0.19", package = "winit" }
rodio = { version = "0.9", default-features = false, features = ["flac", "vorbis", "wav"] }

[features]
profiler = ["thread_profiler/thread_profiler"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3