name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
